CandidatosMaestria/urls.py
from os import name
from django.urls import  path
from . import  views 
app_name = 'CandidatosMaestria'
urlpatterns =  [
    #path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/',views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/',views.ResultsView.as_view(),name='results'),
    path('<int:estatus_id>/asignar/',views.asignar,name='asignar'),
    path('Login/',views.Login,name='Login'),
    path('Registro/',views.Registro,name='Registro'),
    path('',views.index,name='index'),
    path('UploadFile/',views.UploadFile,name='UploadFile'),
    path('Riquisito/<int:requisito_id>/',views.Subir,name='Subir'),
    path('Logout/',views.Logout,name='Logout'),
    path('Maestro/',views.Maestro,name='Maestro'),
    path('ListarCursos/',views.ListarCursos,name='ListarCursos'),
    path('Curso/<int:idCurso>/',views.Curso,name='Curso'), 
    path('Entrevista/',views.entrevista,name='Entrevista'),
    path('CursosDocente/',views.CursosDocente,name='CursosDocente'),
    path('CursoSave/',views.CursoSave,name='CursoSave'),
    path('EntrevistasDocente/',views.EntrevistasDocente,name='EntrevistasDocente'),
    path('Encuesta/<int:identrevista>/',views.Encuestas,name='Encuesta'),
    path('VerEncuesta/<int:identrevista>/',views.VerEncuesta,name='VerEncuesta'),
    path('PdfEncuesta/<int:identrevista>/',views.PdfEncuesta,name='PdfEncuesta'),
    path('SaveEncuesta/',views.SaveEncuesta,name='SaveEncuesta'),
    path('Ponencia/<int:identrevista>/',views.ponencia,name='Ponencia'),
    path('SavePonencia/',views.SavePonencia,name='SavePonencia'),
    path('Verponencia/<int:identrevista>/',views.Verponencia,name='Verponencia'), 
    path('PdfPonencia/<int:identrevista>/',views.PdfPonencia,name='PdfPonencia'), 
    
    
    
]

tecnm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('Candidatos/',include('CandidatosMaestria.urls')),
    path('Alumnos/',include('AlumnosMaestria.urls')),
    
]

if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CandidatosMaestria/models.py
from enum import unique
from pyexpat import model
from xml.dom.minidom import Document
from django.contrib.sessions.backends.db import SessionStore as DBStore
from django.contrib.sessions.base_session import AbstractBaseSession
from django.db import models
from django.db.models.base import Model
from django.db.models.fields import CharField
from django.dispatch import receiver
import os
from django.db.models.signals import post_delete, pre_save, post_save
from django.contrib.auth.models import User
from datetime import datetime

from django.http import Http404



class StatusEntrevista(models.Model):
    Estatus=models.CharField(max_length=45, null=False)
    Descripcion=models.CharField(max_length=85, blank=True, null=True)

    def __str__(self):
        return self.Estatus


class Periodo(models.Model):
    periodo=models.CharField(max_length=50, null=False)

    def __str__(self):
        return self.periodo



class EstatusAspirante(models.Model):
    estatus=models.CharField(max_length=45, null=False)
    descripcion=models.CharField(max_length=85, null=False)

    def __str__(self):
        return self.estatus

class Aspirante(models.Model):
    idaspirante= models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=40, null=False)
    apellidopaterno = models.CharField(max_length=45,null=False)
    apellidomaterno = models.CharField(max_length=45,null=False)
    curp= models.CharField(max_length=18,null=False,unique=True)
    email= models.EmailField(unique=True)
    estatusaspirante = models.ForeignKey(EstatusAspirante, on_delete=models.CASCADE)
    Usuario=models.OneToOneField(User, on_delete=models.CASCADE)
    periodo=models.ForeignKey(Periodo,on_delete=models.CASCADE)
    def __str__(self):
        return self.nombre + " "+ self.apellidopaterno + " " + self.apellidomaterno



class ExamenSeneval(models.Model):
    ICNE = models.IntegerField(null=False)
    PMA = models.IntegerField(null=False)
    PAN = models.IntegerField(null=False)
    ELE = models.IntegerField(null=False)
    CLE = models.IntegerField(null=False)
    MET = models.IntegerField(null=False)
    ICL = models.IntegerField(null=False)
    IUG = models.IntegerField(null=False)
    aspirante = models.OneToOneField(Aspirante, on_delete=models.CASCADE)

class EstatusRequisitoEstudiante(models.Model):
    nombre = models.CharField(max_length=45, null=False) 
    descripcion = models.CharField(max_length=85,null=False)
    def __str__(self):
        return self.nombre



class Requisito(models.Model):
    nombre = models.CharField(max_length=90, null=False)
    descripcion = models.CharField(max_length=300, null= False)
    detalle = models.ManyToManyField(Aspirante, through='DetalleRequisito')
    tamaño=models.DecimalField(null=False, max_digits=4, decimal_places=2)
    def __str__(self):
        return self.nombre
    

def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'Aspirantes/user_{0}_{1}/{2}'.format(instance.aspirante.Usuario,instance.aspirante, filename)

class DetalleRequisito(models.Model):
    aspirante = models.ForeignKey(Aspirante, on_delete=models.CASCADE)
    requisito = models.ForeignKey(Requisito, on_delete=models.CASCADE)
    ruta = models.FileField(upload_to=user_directory_path ,null=True,blank=True)
    carga=models.DateTimeField(blank=True,null=True)
    observaciones = models.CharField(max_length=85,blank=True, null=True)
    estatus = models.ForeignKey(EstatusRequisitoEstudiante, on_delete=models.CASCADE)
    def __str__(self):
        return str(self.aspirante) + str(self.requisito)


@receiver(post_delete, sender=DetalleRequisito)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """
    Elimina el archivo de directorio si se elimina el objeto correspondiente.
    """
    if instance.ruta:
        if os.path.isfile(instance.ruta.path):
            print("path: ", instance.ruta.path)
            os.remove(instance.ruta.path)



@receiver(pre_save, sender=DetalleRequisito)
def auto_delete_file_on_change(sender, instance, **kwargs):
    """
    Elimina el archivo antiguo del directorio cuando se actualiza el objeto correspondiente con un nuevo archivo
    """
    if not instance.pk:
        return False

    old_file = sender.objects.get(pk=instance.pk).ruta

    if old_file:
        new_file = instance.ruta
        if not old_file == new_file:
            if os.path.isfile(old_file.path):
                os.remove(old_file.path)
    else:
        pass



class Docente(models.Model):
    Nombre = models.CharField(max_length=45,null = False)
    ApellidoPaterno= models.CharField(max_length=45,null=False)
    ApellidoMaterno= models.CharField(max_length=45,null=False)
    Curp= models.CharField(max_length=18, null=False, unique=True)
    Rfc=models.CharField(max_length=13,null=False, unique=True)
    CedulaProfesional = models.CharField(max_length=8, null=False, unique=True)
    Email = models.EmailField(null=False, unique=True)
    Usuario=models.OneToOneField(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.Nombre + " "+ self.ApellidoPaterno + " " + self.ApellidoMaterno


class Entrevista(models.Model):
    Fecha = models.DateField()
    HoraInicio = models.TimeField()
    HoraFinal = models.TimeField()
    Observaciones = models.CharField(max_length=45,blank=True, null=True)
    aspirante= models.OneToOneField(Aspirante, on_delete=models.CASCADE)
    detalleentrevistas = models.ManyToManyField(Docente,through='DetalleEntrevista')
    def __str__(self):
        return str(self.aspirante) + '--'+ str(self.Fecha) 

class DetalleEntrevista(models.Model):
    entrevista = models.ForeignKey(Entrevista, on_delete=models.CASCADE)
    docente = models.ForeignKey(Docente, on_delete=models.CASCADE)
    class Meta:
        unique_together = (('entrevista', 'docente'),)
        indexes = [
            models.Index(fields=['entrevista', 'docente']),
        ]

    def __str__(self):
        return str(self.docente)+" -- "+str(self.entrevista)




class CatalogoMaterias(models.Model):
    idMateria=models.AutoField(primary_key=True)
    Materia=models.CharField(max_length=100,null=False)
    Descripcion=models.CharField(max_length=400,null=False)

    def __str__(self):
        return self.Materia



class CursoPropedeutico(models.Model):
    idcurso= models.AutoField(primary_key=True)
    Clave = models.ForeignKey(CatalogoMaterias, on_delete=models.CASCADE)
    FechaInicio= models.DateField()
    FechaFinalizacion= models.DateField()
    HoraInicio= models.TimeField()
    HoraFinalizacion = models.TimeField()
    docente = models.ForeignKey(Docente,on_delete=models.CASCADE)
    periodo=models.ForeignKey(Periodo,on_delete=models.CASCADE)
    def __str__(self):
        return str(self.Clave) +"  "+ str(self.docente)
    



class DetalleAspiranteCurso(models.Model):
    id= models.AutoField(primary_key=True)
    aspirante = models.ForeignKey(Aspirante, on_delete=models.CASCADE)
    cursopropedeutico = models.ForeignKey(CursoPropedeutico, on_delete=models.CASCADE)
    Calificacion= models.IntegerField(null=False)
    
    class Meta:
        unique_together = (('aspirante', 'cursopropedeutico'),)
        indexes = [
            models.Index(fields=['aspirante', 'cursopropedeutico']),
        ]

 






class CatalogoPregunta(models.Model):
    Pregunta= models.CharField(max_length=200, null=False)
    descripcion = models.CharField(max_length=200,blank=True, null=True)

    def __str__(self):
        return self.Pregunta


def user_directory_path2(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'Entrevista/Encuesta/{0}_{1}/{2}'.format(instance.pk,instance.detalleentrevista, filename)


class Encuesta(models.Model):
    FechaHora=models.DateTimeField(blank=True,null=True)
    Observaciones= models.CharField(max_length=100,blank=True, null=True)
    detalleentrevista= models.ForeignKey(DetalleEntrevista,on_delete=models.CASCADE, unique=True)
    Documento = models.FileField(upload_to=user_directory_path2 ,null=True,blank=True)
    detalleEncuesta = models.ManyToManyField(CatalogoPregunta, through='DetalleEncuesta')
    status = models.ForeignKey(StatusEntrevista, on_delete=models.CASCADE)


@receiver(post_delete, sender=Encuesta)
def auto_delete_file_on_delete2(sender, instance, **kwargs):
    """
    Elimina el archivo de directorio si se elimina el objeto correspondiente.
    """
    if instance.Documento:
        if os.path.isfile(instance.Documento.path):
            print("path: ", instance.Documento.path)
            os.remove(instance.Documento.path)



@receiver(pre_save, sender=Encuesta)
def auto_delete_file_on_change2(sender, instance, **kwargs):
    """
    Elimina el archivo antiguo del directorio cuando se actualiza el objeto correspondiente con un nuevo archivo
    """
    if not instance.pk:
        return False

    old_file = sender.objects.get(pk=instance.pk).Documento

    if old_file:
        new_file = instance.Documento
        if not old_file == new_file:
            if os.path.isfile(old_file.path):
                os.remove(old_file.path)
    else:
        pass




class DetalleEncuesta(models.Model):
    encuesta = models.ForeignKey(Encuesta, on_delete=models.CASCADE)
    catalogopreguntas = models.ForeignKey(CatalogoPregunta, on_delete=models.CASCADE)
    Respuesta = models.CharField(max_length=150,blank=True, null=True)



class Criterio(models.Model):
    Criterio=models.CharField(max_length=50,null=False)


    def __str__(self):
        return self.Criterio
    

class Rubrica(models.Model):
    Rubrica=models.CharField(max_length=50,null=False)
    detallecriteriorubricas = models.ManyToManyField(Criterio, through='DetalleCriterioRubrica')
    
    def __str__(self):
        return self.Rubrica



class DetalleCriterioRubrica(models.Model):
    criterio=models.ForeignKey(Criterio,on_delete=models.CASCADE)

CandidatosMaestria/templates/CandidatosMaestria/BaseCandidatosAspirantes.html
{% extends "CandidatosMaestria/BaseCandidatos.html" %}

{% block sidebar %}
<div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <a class="navbar-brand" href="{% url 'CandidatosMaestria:index'%}">TecNM </a>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        

        
        <li class="nav-item">
          <a class="nav-link active">Formatos</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'CandidatosMaestria:ListarCursos'%}">Cursos</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'CandidatosMaestria:Entrevista'%}">Entrevista</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'CandidatosMaestria:Logout'%}">Cerrar Sesion</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
{% endblock sidebar %}

{% block perfil %}
<div id="inner">
    {% if aspirante %}
        <div id="hd">
            <div class="yui-gc">
                <div class="yui-u first">
                    <h1>{{ aspirante.nombre }} {{ aspirante.apellidopaterno}} {{ aspirante.apellidomaterno}}</h1>
                    <h2>Aspirante, {{aspirante.estatusaspirante}}</h2>
                </div>

                <div class="yui-u">
                    <div class="contact-info">
                        
                        <h3>{{aspirante.email}}, {{aspirante.curp}}</h3>
                        
                        <h3></h3>
                        <br>
                        <h3>{{aspirante.periodo}}</h3>
                    </div><!--// .contact-info -->
                </div>
            </div><!--// .yui-gc -->
           

        </div><!--// hd -->

        {% else %}
        <span class="login100-form-title p-b-33">
            Account Login
        </span>
        {% endif %}
    </div>
{% endblock perfil %}

CandidatosMaestria/templates/CandidatosMaestria/BaseCandidatosMaestros.html
{% extends "CandidatosMaestria/BaseCandidatos.html" %}

{% block sidebar %}
<div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <a class="navbar-brand" href="{% url 'CandidatosMaestria:Maestro'%}">TecNM </a>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        

        
        <li class="nav-item">
          <a class="nav-link active">Formatos</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'CandidatosMaestria:CursosDocente'%}">Cursos</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'CandidatosMaestria:EntrevistasDocente'%}">Entrevista</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'CandidatosMaestria:Logout'%}">Cerrar Sesion</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
{% endblock sidebar %}

{% block perfil %}
<div id="inner">
    {% if Docente %}
        <div id="hd">
            <div class="yui-gc">
                <div class="yui-u first">
                    <h1>{{ Docente.Nombre }} {{ Docente.ApellidoPaterno}} {{ Docente.ApellidoMaterno}}</h1>
                    <h2>Docente, {{Docente.Rfc}}</h2>
                </div>

                <div class="yui-u">
                    <div class="contact-info">
                        
                        <h3>{{Docente.Email}}, {{Docente.Curp}}</h3>
                        
                        <h3></h3>
                        <br>
                        <h3>{{Docente.NumeroTelefonico}}</h3>
                    </div><!--// .contact-info -->
                </div>
            </div><!--// .yui-gc -->
           

        </div><!--// hd -->

        {% else %}
        <span class="login100-form-title p-b-33">
            Account Login
        </span>
        {% endif %}
    </div>
{% endblock perfil %}

CandidatosMaestria/templates/CandidatosMaestria/CursoModal.html
{% load static %}


<div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
        <div class="modal-header">
			{% for Alumno in listaalumnocurso %}
						
			{%if forloop.first%}
            <h2 class="modal-title">{{Alumno.cursopropedeutico.Clave}}</h2>
            <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>

        <form  id="form" action="{% url 'CandidatosMaestria:CursoSave' %}" class="form-inline" method="post" enctype="multipart/form-data" >
            {% csrf_token %}
            <div class="modal-body">
                
						<input type="hidden" name="id" value="{{Alumno.cursopropedeutico.idcurso}}">

						<div class="table-responsive"  >
							<table class="table align-middle">
						
								<thead >
									<tr>
										
										<td class="align-top"><h2>Alumno</h2></td>
										<td class="align-top"><h2>Contacto</h2></td>
										<td class="align-top"><h2>Calificacion</h2></td>
						
									</tr>
								 </thead>
									 <tbody>
			{%endif%}

			<tr>
				<td class="align-top">  <p>{{Alumno.aspirante}}</p></td>
				<td class="align-top"><p>{{Alumno.aspirante.email}}</p></td>
				<td class="align-top"><input value="{{ Alumno.Calificacion }}" name="{{ Alumno.id }}" type="number"></td>
			</tr>
					    {% endfor %}

					</tbody>
				</table>
			</div>			
                
            </div>
            <div class="modal-footer">
                <button type="button" id="Cerar" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button class="btn btn-primary" id="enviar" type="submit">Confirmar</button>
            </div>

           
        </form>


    </div>

</div>

CandidatosMaestria/templates/CandidatosMaestria/CursosDocentes.html
{% extends "CandidatosMaestria/BaseCandidatosMaestros.html" %}


{% block Cuerpo %}

<br>
<h2>Cusos Propedeticos</h2>
<br>


{% if listadocentecurso %}
<div class="table-responsive"  >
    <table class="table align-middle">

        <thead >
            <tr>
                
                <td class="align-top">Curso.</td>
                <td class="align-top">Fecha.</td>
                <td class="align-top">Hora.</td>
                <td class="align-top">Ver</td>

            </tr>
         </thead>
             <tbody>

        {% for Curso in listadocentecurso %}
        <tr>
            <td class="align-top">  {{Curso.Clave}}</td>
            <td class="align-top">{{ Curso.FechaInicio }}--{{ Curso.FechaFinalizacion }}</td>
            <td class="align-top">{{ Curso.HoraInicio }}--{{ Curso.HoraFinalizacion }}</td>
            <td class="align-top">
                <button onclick="Abrir_Modal('{% url 'CandidatosMaestria:Curso' Curso.idcurso %}')"  class="btn btn-primary">Calificar</button>
            </td>
        </tr>
        {% endfor %}
             </tbody>
    </table>
</div>

{% endif %}

<br><br><br><br>

<div id="Edicion" class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="Edicion" aria-hidden="true"></div>

{% endblock Cuerpo %}

{% block script %}
<script type="text/javaScript">
    var $ = jQuery.noConflict();
    function Abrir_Modal(url){
        $('#Edicion').load(url,function(){
            $(this).modal('show');
        });
    }
</script>
{% endblock script %}

CandidatosMaestria/templates/CandidatosMaestria/Login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="stylesheet" type="text/css" href="{% static 'CandidatosMaestria/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'CandidatosMaestria/css/main.css' %}">
<!--===============================================================================================-->

</head>
<body>
	
	<div class="limiter">
		
		<div class="container-login100">
			<div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-50">
				<img src="{% static 'CandidatosMaestria/Imagenes/Logos2.png' %}" alt="">
	             <br> <br><br>

				 {% if error_message %}<center><p><strong>{{ error_message }}</strong></p></center> {% endif %}
				<form class="login100-form validate-form" action="{% url 'CandidatosMaestria:Login' %}" method="post">
					{% csrf_token %}
					<span class="login100-form-title p-b-33">
						Cuenta Login
					</span>

					<div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
						<input class="input100" type="text" name="username" placeholder="Usuario">
						<span class="focus-input100-1"></span>
						<span class="focus-input100-2"></span>
					</div>

					<div class="wrap-input100 rs1 validate-input" data-validate="Password is required">
						<input class="input100" type="password" name="password" placeholder="Password">
						<span class="focus-input100-1"></span>
						<span class="focus-input100-2"></span>
					</div>

					<div class="container-login100-form-btn m-t-20">
						<button class="login100-form-btn" type="submit">
							Sign in
						</button>

						

					</div>

					<div class="text-center p-t-45 p-b-4">
						
					</div>

					<div class="text-center">
						<span class="txt1">
							Crear una Cuenta?
						</span>

						<a href="{% url 'CandidatosMaestria:Registro'%}" class="txt2 hov1">
							Registrate
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>
	

	


</body>
</html>

CandidatosMaestria/templates/CandidatosMaestria/Maestro.html
{% extends "CandidatosMaestria/BaseCandidatosMaestros.html" %}

{% block Cuerpo%}
<br><br><br><br><br>
{% endblock Cuerpo %}

CandidatosMaestria/templates/CandidatosMaestria/Registro.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Registro</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="stylesheet" type="text/css" href="{% static 'CandidatosMaestria/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'CandidatosMaestria/css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		
		<div class="container-login100">
			<br> 
			<div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-50">
				
	             <img src="{% static 'CandidatosMaestria/Imagenes/Logos2.png' %}" alt="">
	             <br> <br>

				 {% if error_message %}<center><p><strong>{{ error_message }}</strong></p></center> {% endif %}
				<form class="login100-form validate-form" action="{% url 'CandidatosMaestria:Registro' %}" method="post">
					{% csrf_token %}
					<span class="login100-form-title p-b-33">
						Registrar Cuenta
					</span>

					<div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
						<input required class="input100" type="text" name="username" placeholder="Usuario">
						<span class="focus-input100-1"></span>
						<span class="focus-input100-2"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
						<input required class="input100" type="email" name="email" placeholder="Email">
						<span class="focus-input100-1"></span>
						<span class="focus-input100-2"></span>
					</div>

					<div class="wrap-input100 rs1 validate-input" data-validate="Password is required">
						<input required class="input100" type="password" name="password" placeholder="Password">
						<span class="focus-input100-1"></span>
						<span class="focus-input100-2"></span>
					</div>

					<div class="wrap-input100 rs1 validate-input" data-validate="Password is required">
						<input required class="input100" type="text" name="nombre" placeholder="Nombre">
						<span class="focus-input100-1"></span>
						<span class="focus-input100-2"></span>
					</div>

					<div class="wrap-input100 rs1 validate-input" data-validate="Password is required">
						<input required class="input100" type="text" name="apellidopaterno" placeholder="Apellido Paterno">
						<span class="focus-input100-1"></span>
						<span class="focus-input100-2"></span>
					</div>

					<div class="wrap-input100 rs1 validate-input" data-validate="Password is required">
						<input  required class="input100" type="text" name="apellidomaterno" placeholder="Apellido Materno">
						<span class="focus-input100-1"></span>
						<span class="focus-input100-2"></span>
					</div>

					<div class="wrap-input100 rs1 validate-input" data-validate="Password is required">
						<input  required class="input100" type="text" name="curp" placeholder="Curp">
						<span class="focus-input100-1"></span>
						<span class="focus-input100-2"></span>
					</div>

					<div class="container-login100-form-btn m-t-20">
						<button class="login100-form-btn" type="submit">
							Registrarse
						</button>

						

					</div>

					<div class="text-center p-t-45 p-b-4">
						
					</div>

					<div class="text-center">
						<span class="txt1">
							Iiniciar Sesion?
						</span>

						<a href="{% url 'CandidatosMaestria:Login'%}" class="txt2 hov1">
							Login
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>
	

	


</body>
</html>

CandidatosMaestria/templates/CandidatosMaestria/detail.html
<form action="{% url 'CandidatosMaestria:asignar' estatusaspirante.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ estatusaspirante.estatus  }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for aspirante in estatusaspirante.aspirante_set.all %}
            <input type="radio" name="aspirante" id="aspirante{{ forloop.counter }}" value="{{ aspirante.id }}">
            <label for="aspirante{{ forloop.counter }}">{{ aspirante.nombre }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
    </form>

CandidatosMaestria/templates/CandidatosMaestria/results.html
<h1>{{ estatusalumno.estatus }}</h1>

<ul>
{% for aspirante in estatusalumno.aspirante_set.all %}
    <li>{{ aspirante.nombre }}  {{ aspirante.apellidopaterno }}  {{ aspirante.apellidomaterno}}</li>
{% endfor %}
</ul>

<a href="{% url 'CandidatosMaestria:detail' estatusalumno.id %}">Asignar denuevo</a>