AlumnosMaestria/urls.py
from django.urls import  path
from . import  views 
app_name = 'AlumnosMaestria'
urlpatterns =  [
    path('', views.index, name='index'),
    path('Login/',views.Login,name='Login'),
    path('Registro/',views.Registro,name='Registro'),
    path('UploadFile/',views.UploadFile,name='UploadFile'),
    path('Riquisito/<int:requisito_id>/',views.Subir,name='Subir'),
      path('Semestre/<int:semestre_id>/',views.VSemestre,name='Semestre'),
    path('Logout/',views.Logout,name='Logout'),
]

tecnm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('Candidatos/',include('CandidatosMaestria.urls')),
    path('Alumnos/',include('AlumnosMaestria.urls')),
    
]

if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AlumnosMaestria/models.py
from django.db import models
from django.db.models.base import Model
from django.dispatch import receiver
import os
from django.db.models.signals import post_delete, pre_save, post_save
from django.contrib.auth.models import User


class Semestre(models.Model):
    semestre=models.CharField(max_length=45, null=False)
    descripcion=models.CharField(max_length=85, null=False)
    def __str__(self):
        return self.semestre


class Periodo(models.Model):
    periodo=models.CharField(max_length=50, null=False)
    
    def __str__(self):
        return self.periodo

class Alumno(models.Model):
    nombre = models.CharField(max_length=40, null=False)
    apellidopaterno = models.CharField(max_length=45,null=False)
    apellidomaterno = models.CharField(max_length=45,null=False)
    curp= models.CharField(max_length=18,null=False,unique=True)
    email= models.EmailField(unique=True)
    NumeroControl=models.IntegerField(null=False, unique=True)
    alumnosemestre = models.ForeignKey(Semestre, on_delete=models.CASCADE)
    Usuario= models.OneToOneField(User, on_delete=models.CASCADE)
    periodo=models.ForeignKey(Periodo,on_delete=models.CASCADE)
    def __str__(self):
        return self.nombre + " "+ self.apellidopaterno + " " + self.apellidomaterno

    

class EstatusRequisitoAlumno(models.Model):
    nombre = models.CharField(max_length=45, null=False) 
    descripcion = models.CharField(max_length=85,null=False)
    def __str__(self):
        return self.nombre


class Requisito(models.Model):
    nombre = models.CharField(max_length=100, null=False)
    descripcion = models.CharField(max_length=600, null= False)
    detalle = models.ManyToManyField(Alumno, through='DetalleRequisito')
    tamallo=models.DecimalField(null=False, max_digits=4, decimal_places=2)
    semestre= models.ForeignKey(Semestre, on_delete=models.CASCADE)
    def __str__(self):
        return self.nombre

def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'Alumnos/user_{0}_{1}/{2}'.format(instance.alumno.Usuario,instance.alumno, filename)

class DetalleRequisito(models.Model):
    ruta = models.FileField(upload_to=user_directory_path ,null=True)
    observaciones = models.CharField(max_length=95,blank=True, null=True)
    carga=models.DateTimeField(blank=True,null=True)
    alumno = models.ForeignKey(Alumno, on_delete=models.CASCADE)
    requisito = models.ForeignKey(Requisito, on_delete=models.CASCADE)
    estatusrequisitoalumno = models.ForeignKey(EstatusRequisitoAlumno, on_delete=models.CASCADE)


@receiver(models.signals.post_delete, sender=DetalleRequisito)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """
    Elimina el archivo de directorio si se elimina el objeto correspondiente.
    """
    if instance.ruta:
        if os.path.isfile(instance.ruta.path):
            print("path: ", instance.ruta.path)
            os.remove(instance.ruta.path)



@receiver(models.signals.pre_save, sender=DetalleRequisito)
def auto_delete_file_on_change(sender, instance, **kwargs):
    """
    Elimina el archivo antiguo del directorio cuando se actualiza el objeto correspondiente con un nuevo archivo
    """
    if not instance.pk:
        return False

    old_file = sender.objects.get(pk=instance.pk).ruta

    if old_file:
        new_file = instance.ruta
        if not old_file == new_file:
            if os.path.isfile(old_file.path):
                os.remove(old_file.path)
    else:
        pass






@receiver(post_save, sender=Requisito, dispatch_uid="update_stock_count") 
def update_requisito(sender, instance, **kwargs):


    my_objects = list(DetalleRequisito.objects.filter(requisito=instance))
    if not my_objects:
        statusR = EstatusRequisitoAlumno.objects.get(pk=1)
    
        ListaAlumno = Alumno.objects.all()
        for alumno01 in ListaAlumno:
             detalle = DetalleRequisito.objects.create(alumno=alumno01,requisito=instance,estatusrequisitoalumno=statusR,observaciones=" ")
        detalle.save()     

    post_save.disconnect(update_requisito, sender=Requisito)
    post_save.connect(update_requisito, sender=Requisito)


@receiver(post_save, sender=Alumno, dispatch_uid="update_Alumno_count") 
def New_Alumno(sender, instance, **kwargs):


    my_objects = list(DetalleRequisito.objects.filter(alumno=instance))
    if not my_objects:
        statusR = EstatusRequisitoAlumno.objects.get(pk=1)
    
        ListaRequisitos = Requisito.objects.all()
        for requisitoN in ListaRequisitos:
             detalle = DetalleRequisito.objects.create(alumno=instance,requisito=requisitoN,estatusrequisitoalumno=statusR,observaciones=" ")
        detalle.save()     

    post_save.disconnect(New_Alumno, sender=Alumno)
    post_save.connect(New_Alumno, sender=Alumno)

AlumnosMaestria/views.py
from django.contrib.auth import authenticate, login, logout
from datetime import datetime
from django.core import exceptions
from django.http.response import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.contrib.auth.models import User
from django.db import IntegrityError


from .models import Alumno,DetalleRequisito, Periodo, Semestre,EstatusRequisitoAlumno,Requisito

def index(request):
    if request.user.is_authenticated:

        try:
            alumno01 = Alumno.objects.get(Usuario=request.user)
        except Alumno.DoesNotExist:
            return HttpResponseRedirect(reverse('AlumnosMaestria:Logout'))
        
        requisitossemestre = Requisito.objects.order_by('pk').filter(semestre=alumno01.alumnosemestre)
        listasemestre= Semestre.objects.order_by('pk') 
        ListaRequisitos = []

        
        for requisitos in requisitossemestre:
            ListaRequisitos.append(get_object_or_404(DetalleRequisito,alumno=alumno01, requisito=requisitos) )
        return render(request,'AlumnosMaestria/index.html',{'alumno':alumno01,'ListaRequisitos':ListaRequisitos,'listasemestre':listasemestre})
        
    return HttpResponseRedirect(reverse('AlumnosMaestria:Login'))


def Login(request):
    
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('AlumnosMaestria:index'))
        
    if request.method=='POST':
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('AlumnosMaestria:index'))
        else:
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                try:
                    alumno = Alumno.objects.get(Usuario=user)
                except Alumno.DoesNotExist:
                    logout(request)
                    return render(request,'AlumnosMaestria/Login.html',{'error_message':'La Cuenta No Tiene Accesso'})
                return HttpResponseRedirect(reverse('AlumnosMaestria:index'))
            else:
                return render(request,'AlumnosMaestria/Login.html',{'error_message':'Cuenta o Contraseña Equivocada'})
    else:
        return render(request, 'AlumnosMaestria/Login.html')
    
def Registro(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('AlumnosMaestria:index'))
    else:
        if request.method=='POST':
            username = request.POST['username']
            password = request.POST['password']
            email= request.POST['email']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                return render(request, 'AlumnosMaestria/Registro.html',{'error_message':'El usuario ya Existe'})
            
            user = User.objects.create_user(username,email,password)
            semestre = get_object_or_404(Semestre, pk=1)
            periodoA= Periodo.objects.order_by('pk').last()
            try: 
                alumno = Alumno.objects.create(nombre=request.POST['nombre'],apellidopaterno=request.POST['apellidopaterno'],apellidomaterno=request.POST['apellidomaterno'],curp=request.POST['curp'],email=user.email,NumeroControl=request.POST['numerocontrol'], alumnosemestre=semestre,Usuario=user,periodo=periodoA)
            except 	IntegrityError:
                user.delete()
                return render(request, 'AlumnosMaestria/Registro.html',{'error_message':'El verifique sus informacion'})
            
            
            
            return HttpResponseRedirect(reverse('AlumnosMaestria:Login'))
        else:
            return render(request, 'AlumnosMaestria/Registro.html')
        
  


def UploadFile(request):


    if request.method == "POST":
        
        # Fetching the form data
        

        # Saving the information in the database
        if request.FILES:
            fecha=datetime.now()
            requitisoid = request.POST['id']
            ListaRequisitos=get_object_or_404(DetalleRequisito,id=requitisoid)
            status =get_object_or_404(EstatusRequisitoAlumno,pk=2)
            ListaRequisitos.ruta = request.FILES['uploadedFile']
            ListaRequisitos.estatusrequisitoalumno=status
            ListaRequisitos.carga=fecha
            ListaRequisitos.observaciones=" "
            ListaRequisitos.save()
        else:
            return HttpResponseRedirect(reverse('AlumnosMaestria:index'))

    return HttpResponseRedirect(reverse('AlumnosMaestria:index'))

def Subir(request,requisito_id):
    requisitoAlumno= get_object_or_404(DetalleRequisito,pk=requisito_id)

    return render(request, 'AlumnosMaestria/Archivos.html',{'requisito_id':requisitoAlumno.id,'Descripcion':requisitoAlumno.requisito.descripcion,'size':(requisitoAlumno.requisito.tamallo * 1000000)})

def VSemestre(request,semestre_id):
    if request.user.is_authenticated:

        try:
            alumno01 = Alumno.objects.get(Usuario=request.user)
        except Alumno.DoesNotExist:
            return HttpResponseRedirect(reverse('AlumnosMaestria:Logout'))
        requisitossemestre = Requisito.objects.filter(semestre=semestre_id)
        listasemestre= Semestre.objects.all() 
        ListaRequisitos = []
        
        for requisitos in requisitossemestre:
            ListaRequisitos.append(get_object_or_404(DetalleRequisito,alumno=alumno01, requisito=requisitos) )
        return render(request,'AlumnosMaestria/index.html',{'alumno':alumno01,'ListaRequisitos':ListaRequisitos,'listasemestre':listasemestre})
        
    return HttpResponseRedirect(reverse('AlumnosMaestria:Login'))



def Logout(request):
    if request.user.is_authenticated:
            logout(request)
            return HttpResponseRedirect(reverse('AlumnosMaestria:Login'))
    return HttpResponseRedirect(reverse('AlumnosMaestria:Login'))

AlumnosMaestria/templates/AlumnosMaestria/Archivos.html
{% load static %}


<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h2 class="modal-title"> Cargar Documento</h2>
            <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>

        <form  id="form" action="{% url 'AlumnosMaestria:UploadFile' %}" method="post" enctype="multipart/form-data" >
            {% csrf_token %}
            <div class="modal-body">
                <input class="form-control form-control-lg" id="formFileLg"  type="file" name="uploadedFile" size="{{size}}">
                <input type="hidden" name="id" value="{{requisito_id}}">
                <br><br><br>
                <p class="text-center" class="font-weight-bold">{{Descripcion}}</p>
                <br><br><br>
                <script src="{% static 'AlumnosMaestria/Java/Validar.js' %}"></script>
            </div>
            <div class="modal-footer">
                <button type="button" id="Cerar" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button class="btn btn-primary" id="enviar" type="submit">Confirmar</button>
            </div>

            
        </form>


    </div>

</div>

AlumnosMaestria/templates/AlumnosMaestria/index.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>

	<title>Perfil| Alumnno</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />

	<meta name="keywords" content="" />
	<meta name="description" content="" />
	
   
	<link href="{% static 'AlumnosMaestria/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
	
	<link rel="stylesheet" type="text/css" href="{% static 'AlumnosMaestria/bootstrap/css/bootstrap.css' %}" media="all" />
    
	<link rel="stylesheet" type="text/css" href="{% static 'CandidatosMaestria/css/resume.css' %}" media="all" />
    <link rel="stylesheet" type="text/css" href="{% static 'AlumnosMaestria/bootstrap/css/bootstrap-utilities.css' %}" media="all" />
	
<script src="{% static 'AlumnosMaestria/bootstrap/js/bootstrap.bundle.min.js' %}" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<script src="{% static 'AlumnosMaestria/Java/jquery-3.6.0.min.js' %}"></script>
	
</head>



<body>
	<img src="{% static 'AlumnosMaestria/Imagenes/Logos3.png' %} " class="img-fluid" alt="Responsive image" >
	<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
		<symbol id="bootstrap" viewBox="0 0 118 94">
		  <title>Bootstrap</title>
		  <path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"></path>
		</symbol>
		<symbol id="facebook" viewBox="0 0 16 16">
		  <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
		</symbol>
		<symbol id="instagram" viewBox="0 0 16 16">
			<path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
		</symbol>
		<symbol id="twitter" viewBox="0 0 16 16">
		  <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
		</symbol>
	  </svg>

	<nav class="navbar navbar-expand-lg navbar-light bg-light">
		<div class="container-fluid">
		  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		  </button>
		  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
			<a class="navbar-brand" href="{% url 'AlumnosMaestria:index'%}">TecNM </a>
			<ul class="navbar-nav me-auto mb-2 mb-lg-0">
			  <li class="nav-item">
				<a class="nav-link active" aria-current="page" href="#">Home</a>
			  </li>
			  {% if listasemestre %}
	
			  <li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
				  Plan
				</a>
				<ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
			  {% for semestre in listasemestre %}
	
				  <li><a class="dropdown-item" href="{% url 'AlumnosMaestria:Semestre' semestre.id %}">{{semestre.semestre}}</a></li>
	
			  {% endfor %}
			</ul>
	
			</li>
	
			  {% else %}
	
			  {% endif %}
	
			  
			  <li class="nav-item">
				<a class="nav-link disabled">Formatos</a>
			  </li>
			  <li class="nav-item">
				<a class="nav-link active" href="{% url 'AlumnosMaestria:Logout'%}">Cerrar Sesion</a>
			  </li>
			</ul>
			<form class="d-flex">
			  <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
			  <button class="btn btn-outline-success" type="submit">Search</button>
			</form>
		  </div>
		</div>
	
	
	  </nav>

	  <br>

	  <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
		<div class="carousel-inner">
		  <div class="carousel-item active">
			<img src="{% static 'AlumnosMaestria/Imagenes/C1.jpg' %}" class="d-block w-100" alt="...">
		  </div>
		  <div class="carousel-item">
			<img src="{% static 'AlumnosMaestria/Imagenes/C2.jpg' %}" class="d-block w-100" alt="...">
		  </div>
		  <div class="carousel-item">
			<img src="{% static 'AlumnosMaestria/Imagenes/C3.jpg' %}" class="d-block w-100" alt="...">
		  </div>
		  <div class="carousel-item">
			<img src="{% static 'AlumnosMaestria/Imagenes/C4.jpg' %}" class="d-block w-100" alt="...">
		  </div>
		  <div class="carousel-item">
			<img src="{% static 'AlumnosMaestria/Imagenes/C5.jpg' %}" class="d-block w-100" alt="...">
		  </div>
		</div>
		<button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
		  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
		  <span class="visually-hidden">Previous</span>
		</button>
		<button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
		  <span class="carousel-control-next-icon" aria-hidden="true"></span>
		  <span class="visually-hidden">Next</span>
		</button>
	  </div>

     
	  
	



	  
      <div id="Contenedor10">

		<div id="inner">
		{% if alumno %}
			<div id="hd">
				<div class="yui-gc">
					<div class="yui-u first">
						<h1>{{ alumno.nombre }} {{ alumno.apellidopaterno}} {{ alumno.apellidomaterno}}</h1>
						<h2>alumno, {{alumno.alumnosemestre}}</h2>
					</div>
	
					<div class="yui-u">
						<div class="contact-info">
							
							<h3>{{alumno.email}}, {{alumno.curp}}</h3>
							
							<h3></h3>
							<br>
							<h3>Periodo: {{alumno.periodo}}</h3>
						</div><!--// .contact-info -->
					</div>
				</div><!--// .yui-gc -->
			   

			</div><!--// hd -->
		</div>
	  

        {% else %}
				    <span class="login100-form-title p-b-33">
				        Account Login
				    </span>
		{% endif %}



		{% if ListaRequisitos %}
		{% for requisito in ListaRequisitos %}

		{% if forloop.first %}
		<div class="table-responsive"  >
			<br>
			<h2>Requisitos {{requisito.requisito.semestre}}</h2>
		    <br>
			<table class="table align-middle">

				<thead >
					<tr>
						
						<td class="align-top">Requisito.</td>
						<td class="align-top">Estatus.</td>
						<td class="align-top">Observaciones.</td>
						<td class="align-top">Documento.</td>
	
					</tr>
				 </thead>
				     <tbody>
		{% endif %}

				
				<tr>
					


					
					<td class="align-top">  <span>{{requisito.requisito}}</span> </td>

					
					
					<td class="align-top">{{requisito.estatusrequisitoalumno}}</td>
					<td class="align-top">{{requisito.observaciones}}</td>
					
					     <td class="align-top">
							{% if requisito.estatusrequisitoalumno.id != 1 %}
								 <a class="btn btn-outline-info" href="http://192.168.1.132:8080/media/{{ requisito.ruta }}" role="button">Ver</a>
							{% endif %}
							{% if requisito.estatusrequisitoalumno.id != 4 %}
							    <button onclick="Abrir_Modal('{% url 'AlumnosMaestria:Subir' requisito.id %}')"  class="btn btn-primary">Subir</button>


					        {% endif %}
						
						</td>
					
						 
					

					
				    

				</tr>
			    {% endfor %}
			         </tbody>
			</table>
		  </div>

		{% endif %}

		<br><br><br><br>

		<div class="modal fade" id="Edicion" tabindex="-1" role="dialog" aria-labelledby="Edicion" aria-hidden="true"> </div>

		
	
	
	</div>


		<div class="container">
			<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
			  <div class="col-md-4 d-flex align-items-center">
				<a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
				  <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"/></svg>
				</a>
				<span class="text-muted">&copy; 2022 TecNM Campus Acapulco - Todos los Derechos Reservados</span>
			  </div>
		  
			  <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
				<li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"/></svg></a></li>
				<li class="ms-3"><a class="text-muted" href="https://instagram.com/tecnmacapulco?utm_medium=copy_link"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"/></svg></a></li>
				<li class="ms-3"><a class="text-muted" href="https://www.facebook.com/TecNMAcapulco/"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"/></svg></a></li>
			  </ul>
			</footer>
		  </div>


		  

		  <script type="text/javaScript">
			var $ = jQuery.noConflict();
			function Abrir_Modal(url){
				$('#Edicion').load(url,function(){
					$(this).modal('show');
				});
			}


			
		</script>
		
		
</body>
</html>